global:
  enabled: true
  tlsDisable: true
  serverTelemetry:
    prometheusOperator: true

server:
  image:
    repository: "hashicorp/vault-enterprise"
    tag: "1.12.1-ent"
  enterpriseLicense:
    secretName: ent-license
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
    config: |
      listener "tcp" {
        tls_disable = 1
        address     = "0.0.0.0:8200"
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }

      telemetry {
        prometheus_retention_time = "30s",
        disable_hostname = true
      }
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: local-storage
    mountPath: /vault/data
